name: Build Docker Image - Release
on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse git tag
        run: echo ::set-output name=GITHUB_TAG::${GITHUB_REF#refs/tags/}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args:
            GIT_REF: ${{ GITHUB_TAG }}
          tags:
            - snowblossom/snowblossom:latest
            - snowblossom/snowblossom:${{ GITHUB_SHA }}
            - snowblossom/snowblossom:${{ GITHUB_TAG }}
